### ISSUE TITLE
Move docs to wiki?

### ISSUE THREAD

**Issue by pangelo** [altLab/altBot#13]
We have a `doc/`folder on the repository for project documentation, and it's not a good idea to keep project docs spread around.
 
Do you think we should move all the docs to the wiki?

Also, the existing docs need an update, but that is another issue :)

**Comment by jpralves** [comment]
No. The project doesn't require a wiki. Better keep it in simple documents on the doc folder.

**Comment by X3msnake** [comment]
Agree
